services:
  # Container PHP (App)
  toko-utama-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: toko_utama_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - global_proxy

  # Container Nginx (Web)
  toko-utama-web:
    image: nginx:alpine
    container_name: toko_utama_web
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - toko-utama-app
    networks:
      - global_proxy

networks:
  global_proxy:
    external: true